# schemagen_mca.py

'''Generate SQL that will create a suitable schema for storing data from ATOC
.MCA timetable files. This is done dynamically to ensure it keeps in sync with
the definitions in nrcif.py and nrcif_fields.py'''

from nrcif_records import layouts

import argparse, contextlib

SCHEMA = "mca"

parser = argparse.ArgumentParser()
parser.add_argument("DDL", help = "The destination for the SQL DDL file (default schema_mca_ddl.gen.sql)",
                            nargs = "?", default = "schema_mca_ddl.gen.sql", type=argparse.FileType("w"))
parser.add_argument("CONS", help = "The destination for the SQL constraints & indexes file (default schema_mca_cons.gen.sql)",
                            nargs = "?", default = "schema_mca_cons.gen.sql", type=argparse.FileType("w"))

args = parser.parse_args()

with contextlib.closing(args.DDL) as DDL, contextlib.closing(args.CONS) as CONS:

    DDL.write('''-- SQL DDL for data extracted from ATOC .MCA timetable files in
-- NR CIF format. Auto-generated by schemagen_mca.py\n\n''')

    CONS.write('''-- SQL constraints & indexes definitions for data extracted from ATOC .MCA timetable files in
-- NR CIF format. Auto-generated by schemagen_mca.py\n\n''')

    DDL.write("CREATE SCHEMA {0};\nSET search_path TO {0},public;\n\n".format(SCHEMA))
    CONS.write("SET search_path TO {0},public;\n\n".format(SCHEMA))

    DDL.write('''-- The BS, BX and TN records are stored in the same table\n''')
    DDL.write("CREATE TABLE basic_schedule (\n")

    DDL.write(layouts['BS'].generate_sql_ddl()+",\n")
    DDL.write(layouts['BX'].generate_sql_ddl()+",\n")
    DDL.write(layouts['TN'].generate_sql_ddl())

    DDL.write("\n\t);\n\n")

    CONS.write("ALTER TABLE basic_schedule ADD PRIMARY KEY(train_uid, date_runs_from, stp_indicator);\n")

    DDL.write('''-- The LO, LI, CR, LT and LN tables all have a header added to relate
-- them to the relevant train\n''')

    route_template = '''CREATE TABLE {} (
\ttrain_uid\t\tCHAR(6),
\tdate_runs_from\tDATE,
\tstp_indicator\tCHAR(1),
\tloc_order\t\tINTEGER,
'''
    route_pk = '''ALTER TABLE {0} ADD PRIMARY KEY (train_uid, date_runs_from, stp_indicator, loc_order);
ALTER TABLE {0} ADD FOREIGN KEY (train_uid, date_runs_from, stp_indicator)
    REFERENCES basic_schedule (train_uid, date_runs_from, stp_indicator) DEFERRABLE;

'''

    for i in ('LO', 'LI', 'CR', 'LT', 'LN'):
        tablename = layouts[i].name.lower().replace(" ", "_")
        DDL.write(route_template.format(tablename))
        DDL.write(layouts[i].generate_sql_ddl())
        DDL.write("\n\t);\n\n")
        CONS.write(route_pk.format(tablename))

    normal_template = "CREATE TABLE {} (\n"
    tiploc_pk = "ALTER TABLE {} ADD PRIMARY KEY (tiploc_code);\n\n"

    for i in ('AA', 'TI', 'TA', 'TD'):
        tablename = layouts[i].name.lower().replace(" ", "_")
        DDL.write(normal_template.format(tablename))
        DDL.write(layouts[i].generate_sql_ddl())
        DDL.write("\n\t);\n\n")
        if i != 'AA':
            CONS.write(tiploc_pk.format(tablename))

    DDL.write('''SET search_path TO "$user",public;\n''')
    CONS.write('''SET search_path TO "$user",public;\n''')
