# schemagen_tsi.py

'''Generate SQL that will create a suitable schema for storing data from ATOC
.ZTR timetable files. This is done dynamically to ensure it keeps in sync with
the definitions in nrcif.py, tsi_reader.py and nrcif_fields.py'''

from ..tsi_reader import TSI

def gen_sql(DDL, CONS):

    SCHEMA = "tsi"

    DDL.write('''-- SQL DDL for data extracted from ATOC .TSI interchange files in
-- CSV format. Auto-generated by schemagen_tsi.py\n\n''')

    DDL.write("CREATE SCHEMA {0};\nSET search_path TO {0},public;\n\n".format(SCHEMA))

    DDL.write('''-- Only one table\n''')
    DDL.write("CREATE TABLE tsi (\n")

    first_field = False
    for i in TSI.layout:
        if not first_field:
            first_field=True
        else:
            DDL.write(",\n")
        fieldname = i.name.lower().replace(" ","_")
        DDL.write("\t{0}\t\t{1}".format(fieldname, i.sql_type))

    DDL.write("\n\t);\n\n")

    DDL.write('''SET search_path TO "$user",public;\n\n''')

