# schemagen_msn.py

# Copyright 2013 - 2016, James Humphry

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#

'''Generate SQL that will create a suitable schema for storing data
from ATOC .MSN timetable files. This is done dynamically to ensure it
keeps in sync with the definitions in nrcif.py and nrcif_fields.py'''

from ..msn_records import layouts


def gen_sql(DDL, CONS):

    SCHEMA = "msn"

    DDL.write('-- SQL DDL for data extracted from ATOC .MSN timetable files\n'
              '-- in NR CIF format. Auto-generated by schemagen_msn.py\n\n')

    CONS.write('-- SQL constraints & indexes definitions for data extracted\n'
               '-- from ATOC .MSN timetable files in NR CIF format. \n'
               '-- Auto-generated by schemagen_msn.py\n\n')

    DDL.write('CREATE SCHEMA {0};\n'
              'SET search_path TO {0},public;\n\n'.format(SCHEMA))
    CONS.write("SET search_path TO {0},public;\n\n".format(SCHEMA))

    normal_template = "CREATE TABLE {} (\n"

    for i in ('A', 'L', 'V'):
        tablename = layouts[i].name.lower().replace(" ", "_")
        DDL.write(normal_template.format(tablename))
        DDL.write(layouts[i].generate_sql_ddl())
        DDL.write("\n\t);\n\n")

    CONS.write('ALTER TABLE station_detail ADD PRIMARY KEY(tiploc_code);\n')
    CONS.write('CREATE INDEX idx_stn_detail_stn_name\n'
               '    ON station_detail (station_name);\n')
    CONS.write('CREATE INDEX idx_stn_detail_3alpha \n'
               '    ON station_detail (_3_alpha_code);\n')
    CONS.write('CREATE INDEX idx_stn_alias_stn_name\n '
               '    ON station_alias (station_name);\n')
    CONS.write('CREATE INDEX idx_stn_alias_alias_name\n'
               '    ON station_alias (alias_name);\n')
    CONS.write('ALTER TABLE routeing_groups ADD PRIMARY KEY(group_name);\n')
    CONS.write('\n')

    DDL.write('''SET search_path TO "$user",public;\n\n''')
    CONS.write('''SET search_path TO "$user",public;\n\n''')
